// A $ (document).ready block
$(document).ready(function() {

	console.log("logo test!");

	// CHeck if jQuery and jQueryUI have loaded
	if (jQuery) {  
		console.log("jQuery is loaded"); 
	} else {
		console.log("jQuery is not loaded");
	}

	if (jQuery.ui) {
		console.log("jQueryUI is loaded");
	} else {
		console.log("UI is not loaded");
	}

	/* -- LOGO -- */
		//Logo array
		var logoArray = [
"../../assets/Logos_SVG/7-eleven.svg",
"../../assets/Logos_SVG/AAA_2.svg",
"../../assets/Logos_SVG/ABC.svg",
"../../assets/Logos_SVG/ABH.svg",
"../../assets/Logos_SVG/AEON.svg",
"../../assets/Logos_SVG/ASMI.svg",
"../../assets/Logos_SVG/Accenture.svg",
"../../assets/Logos_SVG/Ace_Hardware.svg",
"../../assets/Logos_SVG/Acer.svg",
"../../assets/Logos_SVG/Action_Man.svg",
"../../assets/Logos_SVG/Adalilar_Kuruyemis.svg",
"../../assets/Logos_SVG/Adidas1007.svg",
"../../assets/Logos_SVG/Adrenalin_Power_Energy_Drink.svg",
"../../assets/Logos_SVG/Agroziv_Pancevo.svg",
"../../assets/Logos_SVG/Agua_Sol.svg",
"../../assets/Logos_SVG/Agua_Xallapan.svg",
"../../assets/Logos_SVG/Ahla_Israel.svg",
"../../assets/Logos_SVG/Air_India_Football_Club_de_Mumbai.svg",
"../../assets/Logos_SVG/Alibaba_com.svg",
"../../assets/Logos_SVG/Ambrozijntje.svg",
"../../assets/Logos_SVG/Android.svg",
"../../assets/Logos_SVG/Apple285.svg",
"../../assets/Logos_SVG/Aquafina.svg",
"../../assets/Logos_SVG/Aquaver.svg",
"../../assets/Logos_SVG/Arby_s_Oven_Mitt.svg",
"../../assets/Logos_SVG/Arco.svg",
"../../assets/Logos_SVG/Arla_Foods_UK.svg",
"../../assets/Logos_SVG/Artigiani_Della_Bufala.svg",
"../../assets/Logos_SVG/Atlanta_Bread_Company.svg",
"../../assets/Logos_SVG/Atlanta_Falcons168.svg",
"../../assets/Logos_SVG/Audi262.svg",
"../../assets/Logos_SVG/Audi265.svg",
"../../assets/Logos_SVG/Autogrill_Spa.svg",
"../../assets/Logos_SVG/Avela_Cafe.svg",
"../../assets/Logos_SVG/Azienda_Agricola_Romano.svg",
"../../assets/Logos_SVG/BAKED_CHEETOS.svg",
"../../assets/Logos_SVG/BP.svg",
"../../assets/Logos_SVG/BUDWEISER_oahsp.svg",
"../../assets/Logos_SVG/Backyard_Burgers.svg",
"../../assets/Logos_SVG/Baeksul(1).svg",
"../../assets/Logos_SVG/Baked.svg",
"../../assets/Logos_SVG/Bakers__and__Chefs.svg",
"../../assets/Logos_SVG/Bakie_s_Bakery.svg",
"../../assets/Logos_SVG/Balaio_de_Lenha.svg",
"../../assets/Logos_SVG/Bama.svg",
"../../assets/Logos_SVG/Banco_do_Brasil.svg",
"../../assets/Logos_SVG/Banvit.svg",
"../../assets/Logos_SVG/Bao_Dimais.svg",
"../../assets/Logos_SVG/Baraka(1).svg",
"../../assets/Logos_SVG/Baraka.svg",
"../../assets/Logos_SVG/Barilla.svg",
"../../assets/Logos_SVG/Barraca_Arabe.svg",
"../../assets/Logos_SVG/Beermates.svg",
"../../assets/Logos_SVG/Best_Buy.svg",
"../../assets/Logos_SVG/Birds_Eye(1).svg",
"../../assets/Logos_SVG/Bireley_s.svg",
"../../assets/Logos_SVG/Bob_s.svg",
"../../assets/Logos_SVG/Bob_s_Big_Boy.svg",
"../../assets/Logos_SVG/Book_It_(1).svg",
"../../assets/Logos_SVG/Borden.svg",
"../../assets/Logos_SVG/Browning275.svg",
"../../assets/Logos_SVG/Bulgarian_Eco_Food.svg",
"../../assets/Logos_SVG/Bull_Basketball_Schools.svg",
"../../assets/Logos_SVG/Burger_King.svg",
"../../assets/Logos_SVG/Busch_Beer.svg",
"../../assets/Logos_SVG/CNN_Sports_Illustrated.svg",
"../../assets/Logos_SVG/Cab_Cola_and_Beer.svg",
"../../assets/Logos_SVG/Cafe_No_Bule.svg",
"../../assets/Logos_SVG/Cafe_Ole.svg",
"../../assets/Logos_SVG/California_Juice.svg",
"../../assets/Logos_SVG/California_Pistachios.svg",
"../../assets/Logos_SVG/Canada_Bread.svg",
"../../assets/Logos_SVG/Canadian_2_for_1_Pizza(1).svg",
"../../assets/Logos_SVG/Canon.svg",
"../../assets/Logos_SVG/Cass_Beer.svg",
"../../assets/Logos_SVG/Cavi_Gourmet.svg",
"../../assets/Logos_SVG/Cenoura_Lapao.svg",
"../../assets/Logos_SVG/Chaleira_Real.svg",
"../../assets/Logos_SVG/Chase_Bank_New.svg",
"../../assets/Logos_SVG/Cheerios.svg",
"../../assets/Logos_SVG/Cheetos.svg",
"../../assets/Logos_SVG/Cheez_Whiz(1).svg",
"../../assets/Logos_SVG/Cheez_Whiz.svg",
"../../assets/Logos_SVG/Chernomor_Beer256.svg",
"../../assets/Logos_SVG/Chevrolet270.svg",
"../../assets/Logos_SVG/Chevrolet275.svg",
"../../assets/Logos_SVG/Chicago_Cubs303.svg",
"../../assets/Logos_SVG/Chick_s_Ricolino.svg",
"../../assets/Logos_SVG/Chili_s.svg",
"../../assets/Logos_SVG/Chiper_s.svg",
"../../assets/Logos_SVG/Chips_Ahoy(1).svg",
"../../assets/Logos_SVG/Chips_Ahoy.svg",
"../../assets/Logos_SVG/Chipy(1).svg",
"../../assets/Logos_SVG/Chipy.svg",
"../../assets/Logos_SVG/Chiquita.svg",
"../../assets/Logos_SVG/Chuck_E_Cheese.svg",
"../../assets/Logos_SVG/Church_s_Chicken(3).svg",
"../../assets/Logos_SVG/Clemente_Jacques.svg",
"../../assets/Logos_SVG/Coalhada_do_Campo.svg",
"../../assets/Logos_SVG/Coca-Cola(1).svg",
"../../assets/Logos_SVG/Coca-Cola(2).svg",
"../../assets/Logos_SVG/Coca-Cola(3).svg",
"../../assets/Logos_SVG/Coca-Cola.svg",
"../../assets/Logos_SVG/Coca-Cola_Light.svg",
"../../assets/Logos_SVG/Coca-Cola_Light_Lemon.svg",
"../../assets/Logos_SVG/Coca-Cola_in_Farsi.svg",
"../../assets/Logos_SVG/Coca_Cola_Zero.svg",
"../../assets/Logos_SVG/Coco_s(1).svg",
"../../assets/Logos_SVG/Conni_Pizzas.svg",
"../../assets/Logos_SVG/Continental_Airlines_BusinessFirst.svg",
"../../assets/Logos_SVG/Converse.svg",
"../../assets/Logos_SVG/Coronel_Mostarda.svg",
"../../assets/Logos_SVG/Corto_de_Malta.svg",
"../../assets/Logos_SVG/Cote_d_Or.svg",
"../../assets/Logos_SVG/Credit_Suisse.svg",
"../../assets/Logos_SVG/Crem_Helado.svg",
"../../assets/Logos_SVG/Cub_Foods.svg",
"../../assets/Logos_SVG/DIET_MOUNTAIN_DEW.svg",
"../../assets/Logos_SVG/DIET_PEPSI.svg",
"../../assets/Logos_SVG/DVD_Video_Audio.svg",
"../../assets/Logos_SVG/D__Doces.svg",
"../../assets/Logos_SVG/Daim.svg",
"../../assets/Logos_SVG/Danone_2.svg",
"../../assets/Logos_SVG/Danone_Danito.svg",
"../../assets/Logos_SVG/Dare(1).svg",
"../../assets/Logos_SVG/Dare(2).svg",
"../../assets/Logos_SVG/Dawtona.svg",
"../../assets/Logos_SVG/DePaul_Blue_Demons273.svg",
"../../assets/Logos_SVG/De_Oya_Cocina.svg",
"../../assets/Logos_SVG/Dean_Foods.svg",
"../../assets/Logos_SVG/DelValle_Classico.svg",
"../../assets/Logos_SVG/DelValle_light.svg",
"../../assets/Logos_SVG/Delicia.svg",
"../../assets/Logos_SVG/Delicyu_s.svg",
"../../assets/Logos_SVG/Detroit_Tigers300.svg",
"../../assets/Logos_SVG/Detroit_Tigers302.svg",
"../../assets/Logos_SVG/Dickens_Cafe.svg",
"../../assets/Logos_SVG/Divino_Mestre.svg",
"../../assets/Logos_SVG/Divino_Sabor.svg",
"../../assets/Logos_SVG/Doce_Desfrute.svg",
"../../assets/Logos_SVG/Dodge_Truck.svg",
"../../assets/Logos_SVG/Dolce_Pasta_Italiana.svg",
"../../assets/Logos_SVG/Dolce__Gabbana33.svg",
"../../assets/Logos_SVG/Domashnya_Kuhnya(2).svg",
"../../assets/Logos_SVG/Domino_s_Pizza(1).svg",
"../../assets/Logos_SVG/Domino_s_Pizza(3).svg",
"../../assets/Logos_SVG/Don_Bettino.svg",
"../../assets/Logos_SVG/Donatos_Pizza.svg",
"../../assets/Logos_SVG/Dragon_Ball_Z.svg",
"../../assets/Logos_SVG/Dragon_Optical.svg",
"../../assets/Logos_SVG/Dragus.svg",
"../../assets/Logos_SVG/EA_Sports.svg",
"../../assets/Logos_SVG/EA_Sports_Big.svg",
"../../assets/Logos_SVG/EFR.svg",
"../../assets/Logos_SVG/Eisberg.svg",
"../../assets/Logos_SVG/El_Fogoncito.svg",
"../../assets/Logos_SVG/El_Globo.svg",
"../../assets/Logos_SVG/Eleven_Beach_Club.svg",
"../../assets/Logos_SVG/Elite.svg",
"../../assets/Logos_SVG/FORMIGA.svg",
"../../assets/Logos_SVG/Fannie_Mae.svg",
"../../assets/Logos_SVG/Ferrari.svg",
"../../assets/Logos_SVG/Ferrari170.svg",
"../../assets/Logos_SVG/Ferrari_Ufficiale.svg",
"../../assets/Logos_SVG/Fiesta_Mart.svg",
"../../assets/Logos_SVG/Flanby.svg",
"../../assets/Logos_SVG/Fleischmann_s.svg",
"../../assets/Logos_SVG/Florida_Gators.svg",
"../../assets/Logos_SVG/Florina.svg",
"../../assets/Logos_SVG/Food__and__Friends.svg",
"../../assets/Logos_SVG/Ford.svg",
"../../assets/Logos_SVG/Ford50.svg",
"../../assets/Logos_SVG/Fornetti.svg",
"../../assets/Logos_SVG/Foster_Farms.svg",
"../../assets/Logos_SVG/Fox_Sports.svg",
"../../assets/Logos_SVG/Fresno_Falcons.svg",
"../../assets/Logos_SVG/Frito-Lay.svg",
"../../assets/Logos_SVG/Fritolay.svg",
"../../assets/Logos_SVG/Gadoua.svg",
"../../assets/Logos_SVG/Gatorade.svg",
"../../assets/Logos_SVG/Giraffas.svg",
"../../assets/Logos_SVG/Gold_Ekmek.svg",
"../../assets/Logos_SVG/Goldman_Sachs.svg",
"../../assets/Logos_SVG/Gorila.svg",
"../../assets/Logos_SVG/Gorki_List(1).svg",
"../../assets/Logos_SVG/Granja_el_Pato.svg",
"../../assets/Logos_SVG/Grill_Fish.svg",
"../../assets/Logos_SVG/GuaraVital(1).svg",
"../../assets/Logos_SVG/HRG_Pastas.svg",
"../../assets/Logos_SVG/HRUStepka(1).svg",
"../../assets/Logos_SVG/Habana_Frapuchinos.svg",
"../../assets/Logos_SVG/Habib_s.svg",
"../../assets/Logos_SVG/Hain.svg",
"../../assets/Logos_SVG/Happy_Joe_s.svg",
"../../assets/Logos_SVG/Hawaiian_Airlines163.svg",
"../../assets/Logos_SVG/Hipercard.svg",
"../../assets/Logos_SVG/Hleb.svg",
"../../assets/Logos_SVG/Hochland.svg",
"../../assets/Logos_SVG/Honda_Automobiles72.svg",
"../../assets/Logos_SVG/Hooters.svg",
"../../assets/Logos_SVG/Hoover_2.svg",
"../../assets/Logos_SVG/Hormel_Foods.svg",
"../../assets/Logos_SVG/Hot__and__Fresh_Pizza_Pizza.svg",
"../../assets/Logos_SVG/Huacalera.svg",
"../../assets/Logos_SVG/Hyatt_Regency_La_Manga.svg",
"../../assets/Logos_SVG/Hydra_Vodka_Water.svg",
"../../assets/Logos_SVG/IDFA.svg",
"../../assets/Logos_SVG/IL_RITROVO_D_ABRUZZO.svg",
"../../assets/Logos_SVG/Il_Forno.svg",
"../../assets/Logos_SVG/Illinois_Fighting_Illini.svg",
"../../assets/Logos_SVG/Illinois_Restaurant_Association.svg",
"../../assets/Logos_SVG/Importali.svg",
"../../assets/Logos_SVG/Internet_Explorer_4.svg",
"../../assets/Logos_SVG/Iomega.svg",
"../../assets/Logos_SVG/Island_Grill.svg",
"../../assets/Logos_SVG/Jack_Daniels.svg",
"../../assets/Logos_SVG/Jacobs(1).svg",
"../../assets/Logos_SVG/Java_University_Program.svg",
"../../assets/Logos_SVG/Jody_Maronis.svg",
"../../assets/Logos_SVG/Juicy.svg",
"../../assets/Logos_SVG/Juicy_cool.svg",
"../../assets/Logos_SVG/KAS.svg",
"../../assets/Logos_SVG/KFC-_Kentucky_Fried_Chicken.svg",
"../../assets/Logos_SVG/Kang.svg",
"../../assets/Logos_SVG/Kasha_Malasha.svg",
"../../assets/Logos_SVG/Kavli.svg",
"../../assets/Logos_SVG/Kawasaki98.svg",
"../../assets/Logos_SVG/Kibon.svg",
"../../assets/Logos_SVG/Kit_Kat.svg",
"../../assets/Logos_SVG/Knorr.svg",
"../../assets/Logos_SVG/Knott_s_Berry_Farm(1).svg",
"../../assets/Logos_SVG/Knott_s_Berry_Farm.svg",
"../../assets/Logos_SVG/Kool-Aid(1).svg",
"../../assets/Logos_SVG/Korzo.svg",
"../../assets/Logos_SVG/Kraft.svg",
"../../assets/Logos_SVG/Krispy_Kreme_Doughnuts.svg",
"../../assets/Logos_SVG/Kroger_s_Food_Store.svg",
"../../assets/Logos_SVG/Kronik_Energy.svg",
"../../assets/Logos_SVG/Kugu_Pastaneleri_Istanbul.svg",
"../../assets/Logos_SVG/LA_CASCINA.svg",
"../../assets/Logos_SVG/La_Estancia_de_los_Tecajetes.svg",
"../../assets/Logos_SVG/La_Lafayette_Ragin_Cajuns(1).svg",
"../../assets/Logos_SVG/La_Lafayette_Ragin_Cajuns.svg",
"../../assets/Logos_SVG/La_Tour.svg",
"../../assets/Logos_SVG/La_Virginia.svg",
"../../assets/Logos_SVG/Las_Delicias.svg",
"../../assets/Logos_SVG/Le_Marche.svg",
"../../assets/Logos_SVG/Letnij_Sad_Pizza.svg",
"../../assets/Logos_SVG/Linda_McCartney_Foods.svg",
"../../assets/Logos_SVG/Liquid_Audio102.svg",
"../../assets/Logos_SVG/Lo_Chef_e_il_Pescatore.svg",
"../../assets/Logos_SVG/Looza.svg",
"../../assets/Logos_SVG/Los_Angeles_Dodgers60.svg",
"../../assets/Logos_SVG/Lotus.svg",
"../../assets/Logos_SVG/Lotus_Bakeries.svg",
"../../assets/Logos_SVG/Louis_Vuitton.svg",
"../../assets/Logos_SVG/Louis_Vuitton97.svg",
"../../assets/Logos_SVG/Louis_Vuitton98.svg",
"../../assets/Logos_SVG/Lunch_Garden.svg",
"../../assets/Logos_SVG/Lunni_Cafes.svg",
"../../assets/Logos_SVG/MDX.svg",
"../../assets/Logos_SVG/MOUNTAIN_DEW_CODE_RED.svg",
"../../assets/Logos_SVG/MOUNTAIN_DEW_LIVE_WIRE.svg",
"../../assets/Logos_SVG/Mac_Doner.svg",
"../../assets/Logos_SVG/Makita103.svg",
"../../assets/Logos_SVG/Maltin_Polar.svg",
"../../assets/Logos_SVG/Mama_Fu_s.svg",
"../../assets/Logos_SVG/Mange.svg",
"../../assets/Logos_SVG/Maseca.svg",
"../../assets/Logos_SVG/Maxwell_House(2).svg",
"../../assets/Logos_SVG/Mayfield_Dairy_Farms.svg",
"../../assets/Logos_SVG/Me__and__Ed_s.svg",
"../../assets/Logos_SVG/MercedesBenz153.svg",
"../../assets/Logos_SVG/Merrill_Lynch.svg",
"../../assets/Logos_SVG/Milkey.svg",
"../../assets/Logos_SVG/Milo(1).svg",
"../../assets/Logos_SVG/Milpa_Real_Tostadas.svg",
"../../assets/Logos_SVG/Minnesota_Vikings.svg",
"../../assets/Logos_SVG/Miracle_Whip(1).svg",
"../../assets/Logos_SVG/Miracle_Whip.svg",
"../../assets/Logos_SVG/Miracoli.svg",
"../../assets/Logos_SVG/Mitsubishi_Motors.svg",
"../../assets/Logos_SVG/Mitsubishi_Motors311.svg",
"../../assets/Logos_SVG/Monster_Energy.svg",
"../../assets/Logos_SVG/Monster_Energy_Beverage_Co_.svg",
"../../assets/Logos_SVG/Monte.svg",
"../../assets/Logos_SVG/Moon_Pie.svg",
"../../assets/Logos_SVG/Morsberry.svg",
"../../assets/Logos_SVG/Mountain_Dew.svg",
"../../assets/Logos_SVG/Mr__Pizza(1).svg",
"../../assets/Logos_SVG/Mr__Pizza.svg",
"../../assets/Logos_SVG/Mrs__GoodCookie.svg",
"../../assets/Logos_SVG/Mustang85.svg",
"../../assets/Logos_SVG/Myllan.svg",
"../../assets/Logos_SVG/NBA.svg",
"../../assets/Logos_SVG/NBC_Sports.svg",
"../../assets/Logos_SVG/NCAA_2K3_College_Basketball.svg",
"../../assets/Logos_SVG/NCAA_Basketball.svg",
"../../assets/Logos_SVG/Na_Zdorovie.svg",
"../../assets/Logos_SVG/Natasha_s_Restaurant.svg",
"../../assets/Logos_SVG/Neru_coffee.svg",
"../../assets/Logos_SVG/Nescafe_Frappe.svg",
"../../assets/Logos_SVG/Nestle.svg",
"../../assets/Logos_SVG/Nike_Football56.svg",
"../../assets/Logos_SVG/Nike_Golf57.svg",
"../../assets/Logos_SVG/Nike_Golf59.svg",
"../../assets/Logos_SVG/Noel.svg",
"../../assets/Logos_SVG/Nom.svg",
"../../assets/Logos_SVG/Norge.svg",
"../../assets/Logos_SVG/Northern_Ireland_Food__and__Drink.svg",
"../../assets/Logos_SVG/Nova_Alimentos.svg",
"../../assets/Logos_SVG/O_Brien_s_Irish_Sandwich_Bar.svg",
"../../assets/Logos_SVG/Opera_O.svg",
"../../assets/Logos_SVG/Orange.svg",
"../../assets/Logos_SVG/Oregon_Ducks81.svg",
"../../assets/Logos_SVG/Oreo(1).svg",
"../../assets/Logos_SVG/Oreo.svg",
"../../assets/Logos_SVG/Orval_Kent.svg",
"../../assets/Logos_SVG/Pabst_Blue_Ribbon.svg",
"../../assets/Logos_SVG/Palma_Juce.svg",
"../../assets/Logos_SVG/Parmalat.svg",
"../../assets/Logos_SVG/Paul__Shark.svg",
"../../assets/Logos_SVG/Pepsi.svg",
"../../assets/Logos_SVG/Pepsi101.svg",
"../../assets/Logos_SVG/Pepsi102.svg",
"../../assets/Logos_SVG/PepsiDiet.svg",
"../../assets/Logos_SVG/Pepsi_Light.svg",
"../../assets/Logos_SVG/Pepsi_Twist.svg",
"../../assets/Logos_SVG/Pepsico.svg",
"../../assets/Logos_SVG/Pepsilogo2008.svg",
"../../assets/Logos_SVG/Perkos_Restaurants.svg",
"../../assets/Logos_SVG/PigglyWiggly.svg",
"../../assets/Logos_SVG/Pisang_Ambon.svg",
"../../assets/Logos_SVG/Pizza_Hut(2).svg",
"../../assets/Logos_SVG/Pizza_Inn(2).svg",
"../../assets/Logos_SVG/Pizza_Inn_2.svg",
"../../assets/Logos_SVG/PlayStation.svg",
"../../assets/Logos_SVG/Plumrose.svg",
"../../assets/Logos_SVG/Pollo_Feliz.svg",
"../../assets/Logos_SVG/Popeyes.svg",
"../../assets/Logos_SVG/Post-it.svg",
"../../assets/Logos_SVG/Post.svg",
"../../assets/Logos_SVG/Post_2.svg",
"../../assets/Logos_SVG/Puma55.svg",
"../../assets/Logos_SVG/Pure.svg",
"../../assets/Logos_SVG/Q_Water.svg",
"../../assets/Logos_SVG/Qatar-petroleum-logo-vector.svg",
"../../assets/Logos_SVG/Ragu.svg",
"../../assets/Logos_SVG/Rama_Lite.svg",
"../../assets/Logos_SVG/Ramkon.svg",
"../../assets/Logos_SVG/Rauch_Bravo.svg",
"../../assets/Logos_SVG/Red_Gold_Quality.svg",
"../../assets/Logos_SVG/Regency123.svg",
"../../assets/Logos_SVG/Restaurant_El_Zapata.svg",
"../../assets/Logos_SVG/Ricolino.svg",
"../../assets/Logos_SVG/Road_Bar(1).svg",
"../../assets/Logos_SVG/Rodnikovy_Kray.svg",
"../../assets/Logos_SVG/Rouzaneh__Daily_.svg",
"../../assets/Logos_SVG/Roxy_Girl.svg",
"../../assets/Logos_SVG/Royal.svg",
"../../assets/Logos_SVG/Ruffles.svg",
"../../assets/Logos_SVG/SIERRA_MIST.svg",
"../../assets/Logos_SVG/SOL_food_oil_saloon.svg",
"../../assets/Logos_SVG/SWA_Sharks.svg",
"../../assets/Logos_SVG/Sa_Cavalcante_Comestiveis.svg",
"../../assets/Logos_SVG/San_Ignacio.svg",
"../../assets/Logos_SVG/Sanitarium(1).svg",
"../../assets/Logos_SVG/Sanitarium.svg",
"../../assets/Logos_SVG/Saudi_Aramco.svg",
"../../assets/Logos_SVG/Schwan_s_Select.svg",
"../../assets/Logos_SVG/Schweppes.svg",
"../../assets/Logos_SVG/Sharky_s_Seafood.svg",
"../../assets/Logos_SVG/Shell40.svg",
"../../assets/Logos_SVG/Shell41.svg",
"../../assets/Logos_SVG/Shell43.svg",
"../../assets/Logos_SVG/Shrimpy75.svg",
"../../assets/Logos_SVG/Sinada.svg",
"../../assets/Logos_SVG/Skiny.svg",
"../../assets/Logos_SVG/Skippy.svg",
"../../assets/Logos_SVG/Smak_Market.svg",
"../../assets/Logos_SVG/Snack_Attack.svg",
"../../assets/Logos_SVG/Snapple.svg",
"../../assets/Logos_SVG/Sormovsky(2).svg",
"../../assets/Logos_SVG/Southern_Methodist_Mustangs.svg",
"../../assets/Logos_SVG/Soy_Restaurant.svg",
"../../assets/Logos_SVG/Spox.svg",
"../../assets/Logos_SVG/Spur.svg",
"../../assets/Logos_SVG/Spy_Bar.svg",
"../../assets/Logos_SVG/Star_Burger.svg",
"../../assets/Logos_SVG/Starbucks_Coffee.svg",
"../../assets/Logos_SVG/Step_Drink.svg",
"../../assets/Logos_SVG/Subway.svg",
"../../assets/Logos_SVG/Suiza_Foods.svg",
"../../assets/Logos_SVG/Sultana.svg",
"../../assets/Logos_SVG/Sunrise(1).svg",
"../../assets/Logos_SVG/SuperFresh.svg",
"../../assets/Logos_SVG/Super_Moli(1).svg",
"../../assets/Logos_SVG/Supermercado_Vila_Lais.svg",
"../../assets/Logos_SVG/Sushiko.svg",
"../../assets/Logos_SVG/Suzuki120.svg",
"../../assets/Logos_SVG/TROPICANA_TWISTER_SODA.svg",
"../../assets/Logos_SVG/Taco_Bell.svg",
"../../assets/Logos_SVG/Taleriai.svg",
"../../assets/Logos_SVG/Tata_Football_Academy_de_Jamshedpur.svg",
"../../assets/Logos_SVG/TeleFood.svg",
"../../assets/Logos_SVG/TelePizza.svg",
"../../assets/Logos_SVG/Tentissimo.svg",
"../../assets/Logos_SVG/Terra_Mia.svg",
"../../assets/Logos_SVG/Terrasamba.svg",
"../../assets/Logos_SVG/Tete_Restaurant.svg",
"../../assets/Logos_SVG/Texaco-logo.svg",
"../../assets/Logos_SVG/The_Buzz_Cafe_de_Torreon.svg",
"../../assets/Logos_SVG/The_Schwan_Food_Company(2).svg",
"../../assets/Logos_SVG/Tia_Rosa.svg",
"../../assets/Logos_SVG/Tropi_Light_Jugos.svg",
"../../assets/Logos_SVG/Tropicana.svg",
"../../assets/Logos_SVG/Tsar_hlib.svg",
"../../assets/Logos_SVG/Turtles.svg",
"../../assets/Logos_SVG/Umpa_Umpa.svg",
"../../assets/Logos_SVG/Unilever.svg",
"../../assets/Logos_SVG/VISA138.svg",
"../../assets/Logos_SVG/VWVolkswagen (1).svg",
"../../assets/Logos_SVG/Vans68.svg",
"../../assets/Logos_SVG/Varanda.svg",
"../../assets/Logos_SVG/Vegemite.svg",
"../../assets/Logos_SVG/Velveeta.svg",
"../../assets/Logos_SVG/Vitol.svg",
"../../assets/Logos_SVG/Volkswagen50.svg",
"../../assets/Logos_SVG/Vollkornbackerei_Niemand.svg",
"../../assets/Logos_SVG/Vom_Fass.svg",
"../../assets/Logos_SVG/Walt_Disney_Home_Video.svg",
"../../assets/Logos_SVG/Warner_Bros_Michigan_J_Frog.svg",
"../../assets/Logos_SVG/Wells_Fargo_Bank.svg",
"../../assets/Logos_SVG/Wheat_Thins.svg",
"../../assets/Logos_SVG/WiFi.svg",
"../../assets/Logos_SVG/Wintmolders.svg",
"../../assets/Logos_SVG/Wisk.svg",
"../../assets/Logos_SVG/Yahoo_Sports.svg",
"../../assets/Logos_SVG/Yellow_Pages.svg",
"../../assets/Logos_SVG/adria-magistra-vector-logo.svg",
"../../assets/Logos_SVG/aflac-vector-logo.svg",
"../../assets/Logos_SVG/aia.svg",
"../../assets/Logos_SVG/aig-logo-vector.svg",
"../../assets/Logos_SVG/airbnb-logo-vector.svg",
"../../assets/Logos_SVG/albertsons-logo-vector.svg",
"../../assets/Logos_SVG/allianz-black-vector-logo.svg",
"../../assets/Logos_SVG/amtrak-vector-logo.svg",
"../../assets/Logos_SVG/applebees.svg",
"../../assets/Logos_SVG/avis-vector-logo.svg",
"../../assets/Logos_SVG/banca_generali.svg",
"../../assets/Logos_SVG/banco-de-chile-logo-vector.svg",
"../../assets/Logos_SVG/banco-ge-logo-vector.svg",
"../../assets/Logos_SVG/banco-le„≥n-logo-vector.svg",
"../../assets/Logos_SVG/barbie.svg",
"../../assets/Logos_SVG/batmanlogos.svg",
"../../assets/Logos_SVG/batmanvintage70slogo.svg",
"../../assets/Logos_SVG/batmanvintagelogo_.svg",
"../../assets/Logos_SVG/bazinga.svg",
"../../assets/Logos_SVG/bbva-banco-provincial-vector-logo.svg",
"../../assets/Logos_SVG/beefeater-london-dry-gin-logo-vector.svg",
"../../assets/Logos_SVG/beershotantverpen.svg",
"../../assets/Logos_SVG/best-western-logo-vector.svg",
"../../assets/Logos_SVG/big-lots-logo-vector.svg",
"../../assets/Logos_SVG/black-&-decker-logo-vector.svg",
"../../assets/Logos_SVG/brasilrecca.svg",
"../../assets/Logos_SVG/braun-logo-vector.svg",
"../../assets/Logos_SVG/browning--eps--vector-logo.svg",
"../../assets/Logos_SVG/california-poly-mustangs-vector-logo.svg",
"../../assets/Logos_SVG/canal-9-vector-logo.svg",
"../../assets/Logos_SVG/canon-you-can-vector-logo.svg",
"../../assets/Logos_SVG/carrefour-group-vector-logo.svg",
"../../assets/Logos_SVG/cartier--eps--vector-logo.svg",
"../../assets/Logos_SVG/casper-black-vector-logo.svg",
"../../assets/Logos_SVG/cerveza_bubweiser.svg",
"../../assets/Logos_SVG/chevron-logo-vector.svg",
"../../assets/Logos_SVG/citibank-(.eps)-logo-vector.svg",
"../../assets/Logos_SVG/citybanklogo.svg",
"../../assets/Logos_SVG/clarks-vector-logo.svg",
"../../assets/Logos_SVG/cnbc-vector-logo.svg",
"../../assets/Logos_SVG/comercial-mexicana-logo-vector.svg",
"../../assets/Logos_SVG/convergencia-vector-logo.svg",
"../../assets/Logos_SVG/coors-light-slant-vector-logo.svg",
"../../assets/Logos_SVG/costa-maya-vector-logo.svg",
"../../assets/Logos_SVG/costco-logo-vector.svg",
"../../assets/Logos_SVG/craigslist-logo-vector.svg",
"../../assets/Logos_SVG/credicard-vector-logo.svg",
"../../assets/Logos_SVG/crush-orange-vector-logo.svg",
"../../assets/Logos_SVG/danger-mouse-vector.svg",
"../../assets/Logos_SVG/dcshoessplah.svg",
"../../assets/Logos_SVG/dharma--eps--vector-logo.svg",
"../../assets/Logos_SVG/diners-club-international-logo-vector.svg",
"../../assets/Logos_SVG/discover-network-vector-logo.svg",
"../../assets/Logos_SVG/disneyland-vector-logo.svg",
"../../assets/Logos_SVG/dodge-division-vector-logo.svg",
"../../assets/Logos_SVG/dodgeviper2012logo.svg",
"../../assets/Logos_SVG/dow-logo-vector.svg",
"../../assets/Logos_SVG/dun-&-bradstreet-logo-vector.svg",
"../../assets/Logos_SVG/dungeons---dragons-vector-logo.svg",
"../../assets/Logos_SVG/eventbrite-logo-vector.svg",
"../../assets/Logos_SVG/feelthedifferencebrandnew.svg",
"../../assets/Logos_SVG/fiu_panthers_logo.svg",
"../../assets/Logos_SVG/foot-locker-logo-vector.svg",
"../../assets/Logos_SVG/garmin-logo-vector.svg",
"../../assets/Logos_SVG/giant-eagle-logo-vector.svg",
"../../assets/Logos_SVG/giant-logo-vector.svg",
"../../assets/Logos_SVG/great-eastern-logo-vector.svg",
"../../assets/Logos_SVG/greenbaypackerslogo.svg",
"../../assets/Logos_SVG/habitat-for-humanity-logo-vector.svg",
"../../assets/Logos_SVG/haima.svg",
"../../assets/Logos_SVG/harleylogo.svg",
"../../assets/Logos_SVG/hellokitty.svg",
"../../assets/Logos_SVG/ing-group-vector-logo.svg",
"../../assets/Logos_SVG/inspired_bikes_logo.svg",
"../../assets/Logos_SVG/interac-yellow-vector-logo.svg",
"../../assets/Logos_SVG/interflora-fleurop-vector-logo.svg",
"../../assets/Logos_SVG/iveco-corporation-vector-logo.svg",
"../../assets/Logos_SVG/johndeerelogo.svg",
"../../assets/Logos_SVG/kelloggsspecialk.svg",
"../../assets/Logos_SVG/kickstarter-logo-vector.svg",
"../../assets/Logos_SVG/kmart-vector-logo.svg",
"../../assets/Logos_SVG/kroger-logo-vector.svg",
"../../assets/Logos_SVG/labelbeervector.svg",
"../../assets/Logos_SVG/liberty-mutual-logo-vector.svg",
"../../assets/Logos_SVG/livingsocial-logo-vector.svg",
"../../assets/Logos_SVG/logicspace.svg",
"../../assets/Logos_SVG/logo_bmw.svg",
"../../assets/Logos_SVG/logo_linksys_eps.svg",
"../../assets/Logos_SVG/logofacebookf.svg",
"../../assets/Logos_SVG/logohollister.svg",
"../../assets/Logos_SVG/logowatermarkrwwhite186c.svg",
"../../assets/Logos_SVG/loreal-logo-vector.svg",
"../../assets/Logos_SVG/lowes-company-vector-logo.svg",
"../../assets/Logos_SVG/made-for-ipod-vector.svg",
"../../assets/Logos_SVG/maestro--card-vector-logo.svg",
"../../assets/Logos_SVG/mattel.svg",
"../../assets/Logos_SVG/mercedesbenzlogo2011.svg",
"../../assets/Logos_SVG/metlife-logo-vector.svg",
"../../assets/Logos_SVG/metro-logo-vector.svg",
"../../assets/Logos_SVG/mlbmajorleaguebaseballlogo.svg",
"../../assets/Logos_SVG/mm.svg",
"../../assets/Logos_SVG/mms.svg",
"../../assets/Logos_SVG/mobil-pegasus-logo.svg",
"../../assets/Logos_SVG/moneygram-vector-logo.svg",
"../../assets/Logos_SVG/mozilla_firefox.svg",
"../../assets/Logos_SVG/nationwide-logo-vector.svg",
"../../assets/Logos_SVG/neiman-marcus-logo-vector.svg",
"../../assets/Logos_SVG/news-corporation-logo-vector.svg",
"../../assets/Logos_SVG/nielsen-logo.svg",
"../../assets/Logos_SVG/nike-vector-logo.svg",
"../../assets/Logos_SVG/onedirection.svg",
"../../assets/Logos_SVG/p90x_logo.svg",
"../../assets/Logos_SVG/paypal-vector-logo.svg",
"../../assets/Logos_SVG/prudential-logo.svg",
"../../assets/Logos_SVG/publix-logo-vector.svg",
"../../assets/Logos_SVG/rabobank--eps--vector-logo.svg",
"../../assets/Logos_SVG/radioshack-logo-vector.svg",
"../../assets/Logos_SVG/rag-logo-vector.svg",
"../../assets/Logos_SVG/rbk-reebok-vector-logo.svg",
"../../assets/Logos_SVG/red4color3dstk (1).svg",
"../../assets/Logos_SVG/redbulleps (1).svg",
"../../assets/Logos_SVG/remax---above-the-crowd-vector-logo.svg",
"../../assets/Logos_SVG/riyadh_baladiyah.svg",
"../../assets/Logos_SVG/rolex--eps--vector-logo.svg",
"../../assets/Logos_SVG/ross-logo-vector.svg",
"../../assets/Logos_SVG/sams-club-vector-logo.svg",
"../../assets/Logos_SVG/samsonite-vector-logo.svg",
"../../assets/Logos_SVG/samsung.svg",
"../../assets/Logos_SVG/samsung_galaxy_s4.svg",
"../../assets/Logos_SVG/santander-group-vector-logo.svg",
"../../assets/Logos_SVG/sercome.svg",
"../../assets/Logos_SVG/shell.svg",
"../../assets/Logos_SVG/soundcloud_logo.svg",
"../../assets/Logos_SVG/spar-shop-vector-logo.svg",
"../../assets/Logos_SVG/sports-authority-logo-vector.svg",
"../../assets/Logos_SVG/square-logo-vector.svg",
"../../assets/Logos_SVG/starbucks_2011_true_logo.svg",
"../../assets/Logos_SVG/state-farm-logo-vector.svg",
"../../assets/Logos_SVG/thumbsupfacebooklikesymbol.svg",
"../../assets/Logos_SVG/tous-vector-logo.svg",
"../../assets/Logos_SVG/ugg-vector-logo.svg",
"../../assets/Logos_SVG/united-technologies-logo-vector.svg",
"../../assets/Logos_SVG/v-d-vector-logo.svg",
"../../assets/Logos_SVG/vansoffthewall.svg",
"../../assets/Logos_SVG/versace-jeans-couture-vector-logo.svg",
"../../assets/Logos_SVG/vmon_3d_logo_glow_cmyk_hz_pos_hi.svg",
"../../assets/Logos_SVG/wakefern-logo-vector.svg",
"../../assets/Logos_SVG/warnerhvblack.svg",
"../../assets/Logos_SVG/western-union.svg",
"../../assets/Logos_SVG/winn-dixie-logo-vector.svg",
"../../assets/Logos_SVG/wmt285copy1235sprk1.svg",
"../../assets/Logos_SVG/worldbank-vector-logo.svg",
"../../assets/Logos_SVG/yum!-brands-logo-vector.svg",
"../../assets/Logos_SVG/zumbafitness.svg",
		];

		var SpinCSSAnim = [
			'spin-1',
			'spin-2',
			'spin-3',
			'spin-4'
		];

		var TranslateXCSSAnim = [
			'translateX-1',
			'translateX-2',
			'translateX-3',
			'translateX-4'
		];


			//console.log(logoArray_A[0]);
				var DOM_body = $('body');
				var offsetX = 0;
				var offsetY = 0;


				//append section
				for (i = 0; i < logoArray.length; i++) {

					var randomSpinCSSAnim = SpinCSSAnim[Math.floor(Math.random()*3)];
					var randomTranslateXCSSAnim = TranslateXCSSAnim[Math.floor(Math.random()*3)];

					var $logoImgTest = $('<img class="logo-test"/>'); 
					$logoImgTest.addClass(randomSpinCSSAnim);
					//$logoImgTest.addClass(randomTranslateXCSSAnim);
			    	$logoImgTest.attr('src', logoArray[i]);

			   		offsetY = Math.floor(Math.random()*3000);
			   		offsetX = Math.floor(Math.random()*3000);
			   		var randomZindex = Math.floor(Math.random()*300);
			   		var randomSize = 50 + Math.floor(Math.random()*1000);
			    	//console.log(offset);

			    	$logoImgTest.css({'margin-top': offsetY + 'px',
			    					  'margin-left': offsetX + 'px', 
			    					  'width': randomSize + 'px',
			    					  'zIndex': randomZindex});
			    	DOM_body.append($logoImgTest);
			    	//console.log($logoImgTest);

			    	/*$mainBody_Section.css({"top": new_top + "px", "left": new_left});

			    	if (column_section === (maxColumns_section - 1)) {
			    		row_section++;
			    	}
			    	//append subSection
					for (j = 0; j < 81; j++) {

						// creates remainder
						var column_subSection = j % maxColumns_subSection; // 9

						var new_top_subSection = column_subSection * (subSectionWidth + padding_subSection); //51x51+3
						var new_left_subSection = row_subSection * (subSectionHeight + padding_subSection);

						//console.log("red-square: " + i + ", small-square: " + j + ", " + "top: " + new_top_subSection + ", " + "left: " + new_left_subSection);

						var $mainBodySubSectionWrapper = $('<div class="bodyPart-subSection-wrapper"/>');
						var $mainBodySubSection = $('<div class="bodyPart-subSection"/>');
						
						var pastelColor = randomPastelColor();
						//var randomColor = ('#'+Math.floor(Math.random()*16777215).toString(16));

						$mainBody_Section.append($mainBodySubSectionWrapper);
						$mainBodySubSectionWrapper.append($mainBodySubSection);

						$mainBodySubSectionWrapper.css({"top": new_top_subSection + "px", "left": new_left_subSection + "px"});
						$mainBodySubSection.css({"background-color": pastelColor});

						if (column_subSection === (maxColumns_subSection - 1)) {
			    			//$mainBodySubSectionWrapper.css({"top": 0 + "px", "left": 0 + "px"});
			    			row_subSection++;
						}
					}

					row_subSection = 0;*/
				}	
});










